$(document).ready(function(){
    
		$(".dienthoai").ForceNumericOnly();	
		
		$.post("ajax/ajax_tour.php",{quocgia:1},function(data){			
			$("#tour_trong_nuoc").html(data);				
		})
		$.post("ajax/ajax_tour.php",{quocgia:2},function(data){			
			$("#tour_nuoc_ngoai").html(data);				
		})
		$("#trong_nuoc_tab").click(function(){		
			$(this).parent().parent().children().removeClass("active");	
			$(this).parent().addClass("active");		
			$.post("ajax/ajax_tour.php",{quocgia:1},function(data){	
				$("#tour_trong_nuoc").hide();
				$("#tour_trong_nuoc").html(data);
				$("#tour_trong_nuoc").show("slide",200);			
			})			
		})	
		$("#ngoai_nuoc_tab").click(function(){		
			$(this).parent().parent().children().removeClass("active");	
			$(this).parent().addClass("active");		
			$.post("ajax/ajax_tour.php",{quocgia:2},function(data){	
				$("#tour_nuoc_ngoai").hide();
				$("#tour_nuoc_ngoai").html(data);
				$("#tour_nuoc_ngoai").show("slide",200);			
			})			
		})			
		$("#mien_nam").click(function(){		
			$(this).parent().parent().children().removeClass("active");	
			$(this).parent().addClass("active");		
			$.post("ajax/ajax_tour.php",{quocgia:1,vungmien:1},function(data){	
				$("#tour_trong_nuoc").hide();
				$("#tour_trong_nuoc").html(data);
				$("#tour_trong_nuoc").show("slide",200);			
			})			
		})	
		$("#mien_trung").click(function(){		
			$(this).parent().parent().children().removeClass("active");	
			$(this).parent().addClass("active");		
			$.post("ajax/ajax_tour.php",{quocgia:1,vungmien:2},function(data){	
				$("#tour_trong_nuoc").hide();
				$("#tour_trong_nuoc").html(data);
				$("#tour_trong_nuoc").show("slide",200);			
			})			
		})
		$("#tab_chau_a").click(function(){		
			$(this).parent().parent().children().removeClass("active");	
			$(this).parent().addClass("active");		
			$.post("ajax/ajax_tour.php",{quocgia:2,vungmien:1},function(data){	
				$("#tour_nuoc_ngoai").hide();
				$("#tour_nuoc_ngoai").html(data);
				$("#tour_nuoc_ngoai").show("slide",200);			
			})			
		})
		$("#tab_chau_au").click(function(){		
			$(this).parent().parent().children().removeClass("active");	
			$(this).parent().addClass("active");		
			$.post("ajax/ajax_tour.php",{quocgia:2,vungmien:2},function(data){	
				$("#tour_nuoc_ngoai").hide();
				$("#tour_nuoc_ngoai").html(data);
				$("#tour_nuoc_ngoai").show("slide",200);			
			})			
		})
		$("#tab_khac").click(function(){		
			$(this).parent().parent().children().removeClass("active");	
			$(this).parent().addClass("active");		
			$.post("ajax/ajax_tour.php",{quocgia:2,vungmien:3},function(data){	
				$("#tour_nuoc_ngoai").hide();
				$("#tour_nuoc_ngoai").html(data);
				$("#tour_nuoc_ngoai").show("slide",200);			
			})			
		})
		$("#mien_bac").click(function(){		
			$(this).parent().parent().children().removeClass("active");	
			$(this).parent().addClass("active");		
			$.post("ajax/ajax_tour.php",{quocgia:1,vungmien:3},function(data){	
				$("#tour_trong_nuoc").hide();
				$("#tour_trong_nuoc").html(data);
				$("#tour_trong_nuoc").show("slide",200);				
			})			
		})	
		$(".next_page_in").live("click",function(){
			var page = $(this).attr("page");
			$.post("ajax/ajax_tour.php",{quocgia:1,page:page},function(data){
				$("#tour_trong_nuoc").hide();
				$("#tour_trong_nuoc").html(data);
				$("#tour_trong_nuoc").show("slide",200);
			})
		})
		$(".pre_page_in").live("click",function(){
			var page = $(this).attr("page");
			$.post("ajax/ajax_tour.php",{quocgia:1,page:page},function(data){
				$("#tour_trong_nuoc").hide();
				$("#tour_trong_nuoc").html(data);
				$("#tour_trong_nuoc").show("slide",200);
			})
		})
		$(".next_page_out").live("click",function(){
			var page = $(this).attr("page");
			$.post("ajax/ajax_tour.php",{quocgia:2,page:page},function(data){
				$("#tour_nuoc_ngoai").hide();
				$("#tour_nuoc_ngoai").html(data);
				$("#tour_nuoc_ngoai").show("slide",200);
			})
		})
		$(".pre_page_out").live("click",function(){
			var page = $(this).attr("page");
			$.post("ajax/ajax_tour.php",{quocgia:2,page:page},function(data){
				$("#tour_nuoc_ngoai").hide();
				$("#tour_nuoc_ngoai").html(data);
				$("#tour_nuoc_ngoai").show("slide",200);
			})
		})
	})